export const services = [
  {
    id: 1,
    title: "تسويق قوة وسائل التواص الاجتماعي",
    desc: "تسويق قوة وسائل التواص الاجتماعي: استغل قوة وسائل التواصل الاجتماعي من خلال الاستراتيجيات المخصصة . سنقوم بإدارة على وسائل التواص الاجتماعي وإنشاء محتوى جذاب وتشغيل حملات إعلانية مستهدفة.",
    img: "/service-1.jpeg",
  },
  {
    id: 2,
    title: "التسويق الرقمي",
    desc: "تصفح المشهد الرقمي بفضل إرشادنا الخبير.شنطور استراتيجية تطوير رقمية تشمل تحسين محركات البحث ووسائل التواصل الإجتماعي وتسويق البريد الإلكتروني والمزيد",
    img: "/service-2.jpeg",
  },
  {
    id: 3,
    title: "التسويق",
    desc: "نقدم نهجا شاملا للتسويق يغطي جميع جوانب وجود علامتك التجارية عبر الإنترنت:من إدارة وسائل التواصل الإجتماعي وتحسين محركات البحث لضمان وصول رسالتك إلى الجمهور المناسب في الوقت المناسب",
    img: "/service-3.jpeg",
  },
  {
    id: 4,
    title: "تسويق الموقع الإلكتروني",
    desc: "قم بزيادة العملاء المحتملين من خلال حلول خدمة تسويق الموقع الإلكتروني الفعالة لدينا.من خلال تحسين محركات البحث إلى الإعلان المدفوع بالنقرة سنضمن أن يصل موقعك الإلكتروني إلى إمكاناته المتكاملة",
    img: "/service-4.jpeg",
  },
  {
    id: 5,
    title: "صناعة المحتوى",
    desc: "نحن أيضا متخصصون في إنشاء المحتوى,حيث نصوغ قصصاً جذابة تلقى صدى لدى السوق المستهدف",
    img: "/service-5.jpeg",
  },
  {
    id: 6,
    title: "تصميم الهوية",
    desc: "تصميم شعار وهوية بصرية بشكل أحترافي يعكس هوية علامتك التجارية وسيعمل فريقنا الإبداعي لإنشاء شعار ومحتوى جذاب لن ينسى لهويتك لوسائل التواصل الإجتماعي وحملاتك التسويقية.",
    img: "/service-6.jpeg",
  },
];

//? JOB DATA:
export const jobs = [
  {
    id: 110,
    image: "/ads-image.jpg",
    jobTitle: "Front-end Developer",
    jobCategory: "Developer",
    location: "Cairo,Egypt",
    salary: "3000$",
    applicationDate: "2023-01-01",
    phoneNumber: "1234567890",
  },
  {
    id: 111,
    image: "/ads-image.jpg",
    jobTitle: "Back-end Developer",
    jobCategory: "Developer",
    location: "Cairo,Egypt",
    salary: "3000$",
    applicationDate: "2023-01-01",
    phoneNumber: "1234567890",
  },
  {
    id: 112,
    image: "/ads-image.jpg",
    jobTitle: "Scrum Master",
    jobCategory: "Markiting",
    location: "Cairo,Egypt",
    salary: "3000$",
    applicationDate: "2023-01-01",
    phoneNumber: "1234567890",
  },
  {
    id: 113,
    image: "/ads-image.jpg",
    jobTitle: "Lead Technical Architect",
    jobCategory: "Technology",
    location: "Cairo,Egypt",
    salary: "3000$",
    applicationDate: "2023-01-01",
    phoneNumber: "1234567890",
  },
  {
    id: 114,
    image: "/ads-image.jpg",
    jobTitle: "Data Analytics",
    jobCategory: "Markiting",
    location: "Cairo,Egypt",
    salary: "3000$",
    applicationDate: "2023-01-01",
    phoneNumber: "1234567890",
  },
  {
    id: 115,
    image: "/ads-image.jpg",
    jobTitle: "System Administrator",
    jobCategory: "Technology",
    location: "Cairo,Egypt",
    salary: "3000$",
    applicationDate: "2023-01-01",
    phoneNumber: "1234567890",
  },
  {
    id: 116,
    image: "/ads-image.jpg",
    jobTitle: "Digital Media Strategy",
    jobCategory: "Business",
    location: "Cairo,Egypt",
    salary: "3000$",
    applicationDate: "2023-01-01",
    phoneNumber: "1234567890",
  },
];
